query ($owner: String!, $repo: String!, $number: Int!) {
  repository(owner: $owner, name: $repo) {
    issueOrPullRequest(number: $number) {
      ... on Issue {
        author { __typename login ... on User { databaseId } ... on Bot { databaseId } }
        editor { __typename login ... on User { databaseId } ... on Bot { databaseId } }
      }
      ... on PullRequest {
        author { __typename login ... on User { databaseId } ... on Bot { databaseId } }
        editor { __typename login ... on User { databaseId } ... on Bot { databaseId } }
      }
    }
  }
}
