name: Connect to OpenVPN
description: Fetches VPN credentials from GCP Secret Manager and connects to OpenVPN.
inputs:
  secret:
    description: GCP Secret Manager secret in format project/name
    required: false
    default: kelly-ferrone/github-openvpn
runs:
  using: composite
  steps:

  - name: Get VPN Credentials
    id: creds
    uses: google-github-actions/get-secretmanager-secrets@v3
    with:
      secrets: |-
        openvpn:${{ inputs.secret }}

  - name: Parse Credentials
    id: vpn
    shell: bash
    env:
      SECRET: ${{ steps.creds.outputs.openvpn }}
    run: |
      echo "username=$(echo "$SECRET" | jq -r '.username')" >> $GITHUB_OUTPUT
      echo "password=$(echo "$SECRET" | jq -r '.password')" >> $GITHUB_OUTPUT
      echo "$SECRET" | jq -r '.profile' > "$RUNNER_TEMP/profile.ovpn"

  - name: Install OpenVPN
    id: install
    shell: bash
    run: |
      sudo apt update
      sudo apt install -y openvpn openvpn-systemd-resolved

  - name: Connect to VPN
    uses: kota65535/github-openvpn-connect-action@v2
    with:
      config_file: ${{ runner.temp }}/profile.ovpn
      username: ${{ steps.vpn.outputs.username }}
      password: ${{ steps.vpn.outputs.password }}
