name: Build and push Docker Image
description: Deploy to Kubernetes using Helm
inputs: 
  push:
    description: 'Whether to push the image to DockerHub'
    required: false
    default: 'false'
  username:
    description: 'DockerHub Username'
    required: false
  password:
    description: 'DockerHub Password'
    required: false
  repository:
    description: 'DockerHub Repository'
    required: false
runs:
  using: composite
  steps:
  
  - name: Setup QEMU
    id: setup-qemu
    uses: docker/setup-qemu-action@v3

  - name: Set up Docker Buildx
    id: buildx
    uses: docker/setup-buildx-action@v3

  - name: Set Image Args
    shell: bash
    run: |
      {
        echo "GIT_REF=$(echo ${GITHUB_REF##*/} | sed -e 's/\//_/g')";
        echo "GIT_SHA=$(git rev-parse --short HEAD)";
      } >> $GITHUB_ENV
    
  - name: Login to DockerHub
    id: login-dockerhub
    if: inputs.push == 'true'
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Build and Push
    shell: bash
    env:
      PUSH_FLAG: ${{ (inputs.push == 'true') && '--push' || '' }}
    run: docker buildx bake $PUSH_FLAG

  - name: Docker Hub Description
    uses: peter-evans/dockerhub-description@v4
    if: inputs.push
    with:
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
      repository: ${{ inputs.repository || github.repository }}
